import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FDF5F8',
  },
  headerWrap: {},

  // streak + points
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    marginTop: 10,
    marginBottom: 2,
  },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 6,
    shadowColor: '#C47898',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  statEmoji: {
    fontSize: 15,
  },
  statText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#C47898',
  },

  // date + motivation
  dateLabel: {
    marginTop: 14,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '700',
    color: '#C47898',
    textTransform: 'capitalize',
  },
  motivRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 18,
    marginTop: 10,
    marginBottom: 16,
    gap: 8,
  },
  sparkle: {
    color: '#7B61FF',
    fontSize: 15,
  },
  motivText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
  },
  playBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FDEAF2',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // weather banner
  weatherCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: '#FFF5C2',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  weatherIcon: {
    fontSize: 26,
  },
  weatherCity: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8A6B00',
    marginBottom: 3,
  },
  weatherTip: {
    fontSize: 13,
    color: '#6B5200',
    fontWeight: '500',
    lineHeight: 18,
  },

  // tip card
  tipCard: {
    marginHorizontal: 16,
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#C47898',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  tipCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  tipLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#E8789A',
    letterSpacing: 0.8,
  },
  tipLike: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  tipLikeNum: {
    fontSize: 12,
    color: '#BBB',
    fontWeight: '500',
  },
  tipText: {
    fontSize: 15,
    color: '#555',
    lineHeight: 22,
  },

  // routine card
  routineCard: {
    marginHorizontal: 16,
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#C47898',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  restDayBox: {
    alignItems: 'center',
    paddingVertical: 28,
  },
  restDayEmoji: {
    fontSize: 30,
    marginBottom: 8,
  },
  restDayText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#3A2E35',
    marginBottom: 4,
  },
  restDaySubtext: {
    fontSize: 13,
    color: '#999',
    textAlign: 'center',
  },
  actionSheetBox: {
    backgroundColor: '#fff',
    borderRadius: 18,
    marginHorizontal: 32,
    paddingVertical: 8,
    shadowColor: '#BF789C',
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  actionSheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 18,
  },
  actionSheetText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#3A2E35',
  },
  routineCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  routineCardTitle: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  progressCount: {
    marginLeft: 'auto',
    fontSize: 11,
    fontWeight: '700',
  },
  progressTrack: {
    height: 5,
    backgroundColor: '#F3ECF0',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 16,
  },
  progressFill: {
    height: 5,
    borderRadius: 3,
  },
  completionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F6FFF6',
    borderWidth: 1.5,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  completionEmoji: {
    fontSize: 18,
  },
  completionText: {
    fontSize: 14,
    fontWeight: '700',
  },

  myRoutineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 14,
  },
  myRoutineText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
  },

  // routine item
  routineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 12,
  },
  productThumb: {
    width: 44,
    height: 56,
    borderRadius: 10,
  },
  routineItemContent: {
    flex: 1,
  },
  routineItemText: {
    fontSize: 15,
    color: '#333',
    lineHeight: 21,
  },
  routineItemLabel: {
    fontWeight: '700',
  },
  routineItemBrand: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },

  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    marginTop: 2,
  },
  addRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  addRowText: {
    fontSize: 14,
    fontWeight: '600',
  },
  squareBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // product selector modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 36,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E0E0E0',
    alignSelf: 'center',
    marginBottom: 18,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#2D2D2D',
    marginBottom: 4,
  },
  modalHint: {
    fontSize: 12,
    color: '#999',
    marginBottom: 12,
  },
  modalCategory: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D6A4A4',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  modalProductRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F0F3',
  },
  modalProductRowActive: {
    backgroundColor: '#FDF0F5',
    borderRadius: 12,
  },
  modalProductBrand: {
    fontSize: 11,
    fontWeight: '700',
    color: '#D6A4A4',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  modalProductName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  modalCancel: {
    marginTop: 18,
    alignItems: 'center',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#F7F0F4',
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#BF789C',
  },

  centerBtn: {
    alignSelf: 'center',
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 14,
  },

  // + button
  plusBtn: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // add step modal
  stepInput: {
    backgroundColor: '#FBF5F8',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#333',
    borderWidth: 1.5,
    borderColor: '#F0E0E8',
  },
  stepSaveBtn: {
    marginTop: 18,
    borderRadius: 16,
    overflow: 'hidden',
  },
  stepSaveBtnGradient: {
    paddingVertical: 15,
    alignItems: 'center',
  },
  stepSaveBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },

  // diary modal
  diarySheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    width: '100%',
    maxHeight: '90%',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 36,
  },
  diaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 8,
  },
  diaryTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#2D2D2D',
    flex: 1,
  },
  diaryDate: {
    fontSize: 13,
    fontWeight: '600',
    color: '#D6A4A4',
  },
  diaryClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F5F0F3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  diaryScroll: {
    paddingBottom: 16,
  },
  diaryQuestion: {
    fontSize: 13,
    fontWeight: '700',
    color: '#555',
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  diaryDivider: {
    height: 1,
    backgroundColor: '#F5E8EC',
    marginVertical: 18,
  },
  diaryYesNoRow: {
    flexDirection: 'row',
    gap: 16,
  },
  diaryNoteInput: {
    backgroundColor: '#FBF5F8',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#333',
    borderWidth: 1.5,
    borderColor: '#F0E0E8',
    minHeight: 80,
    textAlignVertical: 'top',
  },

  // diary photos
  diaryPhotosRow: {
    gap: 10,
    paddingBottom: 4,
  },
  diaryPhotoThumb: {
    width: 80,
    height: 100,
    borderRadius: 12,
    backgroundColor: '#F5E8EC',
  },
  diaryPhotoAdd: {
    width: 80,
    height: 100,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E8D0D8',
    borderStyle: 'dashed',
    backgroundColor: '#FDF5F8',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // chips
  chipGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 99,
    borderWidth: 1.5,
    borderColor: '#E8D0D8',
    backgroundColor: '#FDF5F8',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#999',
  },
  chipTextActive: {
    color: '#fff',
  },

  // yes/no
  yesNoRow: {
    flexDirection: 'row',
    gap: 10,
  },
  yesNoBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E8D0D8',
    backgroundColor: '#FDF5F8',
    alignItems: 'center',
  },
  yesNoBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#999',
  },
  yesNoBtnTextActive: {
    color: '#fff',
  },

  // picker modal (selector agregar)
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  pickerSheet: {
    backgroundColor: '#FDF5F8',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    width: '100%',
    shadowColor: '#BF789C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 10,
  },
  pickerTitleBar: {
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 18,
    marginBottom: 16,
  },
  pickerTitleText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  pickerOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    gap: 14,
  },
  pickerOptionIcon: {
    width: 44,
    height: 44,
    borderRadius: 13,
    backgroundColor: '#FDEAF2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerOptionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2D2D2D',
    marginBottom: 2,
  },
  pickerOptionSub: {
    fontSize: 12,
    color: '#AAA',
    fontWeight: '500',
  },
  pickerDivider: {
    height: 1,
    backgroundColor: '#F0E0E8',
    marginVertical: 2,
  },

  // streak modal
  budgetPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: '#FDF0F5',
    borderWidth: 1,
    borderColor: '#F0D5E2',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginTop: 16,
    marginHorizontal: 20,
  },
  budgetPillEmoji: { fontSize: 14 },
  budgetPillText: { fontSize: 13, fontWeight: '600', color: '#BF789C' },
  budgetModalBox: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    width: '100%',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
    shadowColor: '#BF789C',
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  budgetModalTitle: { fontSize: 17, fontWeight: '700', color: '#3A2E35' },
  budgetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#F0E0E8',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  budgetOptionActive: {
    borderColor: '#BF789C',
    backgroundColor: '#FDF0F5',
  },
  budgetOptionEmoji: { fontSize: 22 },
  budgetOptionLabel: { fontSize: 15, fontWeight: '600', color: '#3A2E35' },
  budgetOptionHint: { fontSize: 12, color: '#BF789C', marginTop: 2 },
  streakModalBox: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    width: '100%',
    height: '82%',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 48,
    shadowColor: '#BF789C',
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -4 },
    elevation: 10,
  },
  streakModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  streakPointsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#FDF0F5',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  streakPointsText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#BF789C',
  },
  streakCenter: {
    alignItems: 'center',
    marginBottom: 24,
  },
  streakBigIcon: {
    fontSize: 36,
    marginBottom: 4,
  },
  streakBigNumber: {
    fontSize: 64,
    fontWeight: '800',
    color: '#2D2D2D',
    lineHeight: 72,
  },
  streakLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#CCC',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  streakSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#D6A4A4',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  streakCardsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  streakCard: {
    flex: 1,
    backgroundColor: '#FDF5F8',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  streakCardNumber: {
    fontSize: 26,
    fontWeight: '800',
    color: '#2D2D2D',
  },
  streakCardLabel: {
    fontSize: 12,
    color: '#AAA',
    fontWeight: '600',
    marginTop: 2,
  },
  streakStatsList: {
    backgroundColor: '#FDF5F8',
    borderRadius: 16,
    paddingHorizontal: 16,
  },
  streakStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#F5EBF0',
  },
  streakStatLabel: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  streakStatValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#BF789C',
  },
});
